### ISSUE TITLE
Feature Request: Settings option for using Tab character instead of spaces

### ISSUE THREAD

**Issue by flamewave000** [arcanistzed/acelib#1]
I won't get into the age old debate on if tabs or spaces are better, but I personally prefer tabs and am constantly annoyed that the web dev world seems to have baked in "spaces" as being expected, while the rest of the programming world accepts either or. The Ace Editor appears to be no different and sets the default to spaces and I don't see a setting in the acelib module to change that yet. Could you add a way to toggle the use of the Tab character instead of spaces in the Ace Lib configuration?

**Comment by arcanistzed** [comment]
Hey, sorry for taking so long to get back to you. This already exist. The setting is called "Use Soft Tabs". I'll add a Hint to make this more clear.
